### ISSUE TITLE
[Feature Request]: Event firing after coordinates array has changed (RulerControl)

### ISSUE THREAD

**Issue by tapczan1337** [korywka/mapbox-gl-controls#29]
As of now it has to be done with awkward workarounds.

**Comment by korywka** [comment]
@tapczan1337 2.3.0

![image](https://user-images.githubusercontent.com/988471/117957695-fecc6480-b322-11eb-9c5b-aeb97b9b3bed.png)

I hope this is the event that you asked for :)

Check console at https://korywka.github.io/mapbox-gl-controls/

**Comment by tapczan1337** [comment]
Hello,

thank you for the update and apologize for not giving feedback earlier (just was given a green light to work on this topic again). 

I'm wondering if its possible to fire an event not only when a user adds a new marker but also after a marker gets dragged :ok_hand:

**Comment by korywka** [comment]
@tapczan1337 Hi. Done.

https://github.com/korywka/mapbox-gl-controls/commit/1f77cde8fcc498239f00fe4914f6e4b75e730c33

**Comment by tapczan1337** [comment]
Awesome.
