### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'lineSource.setData')

### ISSUE THREAD

**Issue by xfishernet** [korywka/mapbox-gl-controls#35]
In Rule mode if switch map from street to stallite, I catch this error: 

TypeError: undefined is not an object (evaluating 'lineSource.setData')

**Comment by xfishernet** [comment]
<img width="781" alt="Screenshot 2021-11-16 at 18 06 31" src="https://user-images.githubusercontent.com/5359718/142021538-732c1b68-223b-426c-91a8-954354e31c84.png">

**Comment by korywka** [comment]
I would be happy to reopen if there is more context and activity.
