### ISSUE TITLE
By switching styles, it clears any existing layer

### ISSUE THREAD

**Issue by vcardins** [korywka/mapbox-gl-controls#48]
![2023-02-13 17 41 21](https://user-images.githubusercontent.com/2383329/218616474-145b0361-734c-4036-8c1e-193468b0af2a.gif)

**Comment by korywka** [comment]
It is not bug, it is how mapbox API works :)
One way to bypass this is to draw layers on style.load event: https://github.com/korywka/mapbox-gl-controls/blob/5ca4d76310ed324abc4b76cb465106b118be82e4/example/example.js#L99

Please, let me know if you still need help.

**Comment by vcardins** [comment]
Closing. I ended up using https://github.com/el/style-switcher/pull/27, which has the preserve layers solution implemented.

**Comment by korywka** [comment]
Nice, but keep it mind that preserving layers can cause other bugs. For example, if you change paint properties of street style layers, these layers can be missing in satellite style. This is the reason why it is better to implement this by yourself. But if it works for you - it is cool.
